Спелл чекер.
ChaoticOnyx/BeeStation pull request #64
Opened 2021-06-10 09:41 UTC by Doster-d

Портировал фичу с Оникса, хау ироник.

## Changelog
:cl:
add: Spell Checker added!
/:cl:

2021-06-10 10:32 UTC, Doster-d commented
Исправил русский язык в сохранение чата
![image](https://user-images.githubusercontent.com/63081538/121510322-309f1c80-c9f0-11eb-9723-010c8bcccd09.png)

2021-06-16 13:36 UTC, kreeperHLC requested changes
ПР в Дев ветку, какой ещё Мастер

2021-06-16 13:45 UTC, Doster-d commented
done

2021-06-23 20:30 UTC, kreeperHLC commented
Уже добавлено

2021-06-23 20:30 UTC, closed without merging